import Navbar from "@/components/Navbar";
import type { Metadata } from "next";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={"h-full" + inter.className}>
      <body className="min-h-full">
        <div className="bg-gradient-to-r from-sky-50 to-indigo-50 h-full">
          <Navbar />
          {children}
        </div>
      </body>
    </html>
  );
}
